### PR TITLE
Home page

### PR DESCRIPTION
**Pull request by Naylin15**
# Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: [Conventional Commit](https://conventionalcommits.org/)
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior

Wiki content in the home page of the project site
Issue # N/A

## What is the new behavior
New content in the home page of the project
## Does this PR introduce a breaking change

- [ ] Yes
- [x] No

## Other information

Hi, @ajsb85 

This PR adds new content in the index for the home page

### CODE REVIEW

**Review by ajsb85 — APPROVED** [review]
Reviewed

**Review by ajsb85 — CHANGES_REQUESTED** [review]
Hi, @Gianfranco97 
I prefer to use Markdown instead HTML

**Comment by ajsb85** [comment]
Hi, @Naylin15 
Now you can use Markdown.
Thanks.

**Comment by Naylin15** [comment]
Hi, @ajsb85
Changes made, now the content is in Markdown

**Review by ajsb85 — APPROVED** [review]
Reviewed

**Pull request merged**
